Imports

In [1]:
import numpy as np
import pandas as pd

Exploring Data

In [2]:
dirpath = '../data/tml-data/'

In [3]:
# create a pandas data frame

df = pd.read_csv(f'{dirpath}2000.csv')

df.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,indoor,tourney_date,match_num,winner_id,winner_seed,...,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
0,2000-7308,Adelaide,Hard,32,250,O,20000103,1,E113,1.0,...,2.0,1.0,3.0,59.0,37.0,25.0,13.0,9.0,2.0,4.0
1,2000-7308,Adelaide,Hard,32,250,O,20000103,2,F324,NaN,...,0.0,3.0,5.0,42.0,15.0,13.0,12.0,8.0,0.0,3.0
2,2000-7308,Adelaide,Hard,32,250,O,20000103,3,G352,NaN,...,1.0,26.0,2.0,103.0,59.0,49.0,22.0,16.0,4.0,5.0
3,2000-7308,Adelaide,Hard,32,250,O,20000103,4,G379,7.0,...,4.0,0.0,3.0,49.0,22.0,12.0,8.0,8.0,1.0,6.0
4,2000-7308,Adelaide,Hard,32,250,O,20000103,5,N250,3.0,...,1.0,4.0,2.0,73.0,40.0,25.0,16.0,10.0,7.0,10.0

Augment the data

In [4]:
yr_ends = yr_ends = list(range(2001, 2027))


for yr in yr_ends:

    yr_str = f'{yr}'

    file = dirpath + yr_str + '.csv'

    # create data frame

    df2 = pd.read_csv(file)
    print(f'{file} : {df2.shape} ')

    df = pd.concat([df, df2])


print(f'df shape: {df.shape}')

../data/tml-data/2001.csv : (3311, 50)
../data/tml-data/2002.csv : (3213, 50)
../data/tml-data/2003.csv : (3218, 50)
../data/tml-data/2004.csv : (3288, 50)
../data/tml-data/2005.csv : (3263, 50)
../data/tml-data/2006.csv : (3267, 50)
../data/tml-data/2007.csv : (3192, 50)
../data/tml-data/2008.csv : (3123, 50)
../data/tml-data/2009.csv : (3085, 50)
../data/tml-data/2010.csv : (3030, 50)
../data/tml-data/2011.csv : (3015, 50)
../data/tml-data/2012.csv : (3009, 50)
../data/tml-data/2013.csv : (2944, 50)
../data/tml-data/2014.csv : (2901, 50)
../data/tml-data/2015.csv : (2945, 50)
../data/tml-data/2016.csv : (2970, 50)
../data/tml-data/2017.csv : (2936, 50)
../data/tml-data/2018.csv : (2926, 50)
../data/tml-data/2019.csv : (2806, 50)
../data/tml-data/2020.csv : (1466, 50)
../data/tml-data/2021.csv : (2735, 50)
../data/tml-data/2022.csv : (2918, 50)
../data/tml-data/2023.csv : (2995, 50)
../data/tml-data/2024.csv : (3076, 50)
../data/tml-data/2025.csv : (2944, 50)
../data/tml-data/2026.csv : (2085, 50)
df shape: (80039, 50)

Calculate extra statstistics and append data

In [8]:
# sort the data by chronology. 

df.sort_values(['tourney_date', 'match_num'], ascending=[True, True])

,tourney_id,tourney_name,surface,draw_size,tourney_level,indoor,tourney_date,match_num,winner_id,winner_seed,...,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
0,2000-7308,Adelaide,Hard,32.0,250,O,20000103,1.0,E113,1.0,...,2.0,1.0,3.0,59.0,37.0,25.0,13.0,9.0,2.0,4.0
31,2000-451,Doha,Hard,32.0,250,O,20000103,1.0,K316,1.0,...,3.0,5.0,2.0,83.0,53.0,36.0,17.0,12.0,2.0,4.0
62,2000-891,Chennai,Hard,32.0,250,O,20000103,1.0,T243,NaN,...,3.0,4.0,5.0,57.0,23.0,16.0,13.0,9.0,3.0,7.0
1,2000-7308,Adelaide,Hard,32.0,250,O,20000103,2.0,F324,NaN,...,0.0,3.0,5.0,42.0,15.0,13.0,12.0,8.0,0.0,3.0
32,2000-451,Doha,Hard,32.0,250,O,20000103,2.0,C270,NaN,...,14.0,8.0,5.0,102.0,57.0,41.0,18.0,16.0,2.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2080,2026-422,Cincinnati Masters,Hard,96.0,M,O,20260822,91.0,N0AE,27.0,...,6.0,22.0,3.0,90.0,52.0,43.0,20.0,15.0,1.0,3.0
2081,2026-422,Cincinnati Masters,Hard,96.0,M,O,20260822,92.0,TD51,17.0,...,4.0,4.0,4.0,94.0,49.0,35.0,19.0,12.0,5.0,8.0
2082,2026-422,Cincinnati Masters,Hard,96.0,M,O,20260822,93.0,F0F1,21.0,...,2.0,2.0,1.0,43.0,26.0,19.0,8.0,9.0,1.0,4.0
2083,2026-422,Cincinnati Masters,Hard,96.0,M,O,20260823,94.0,TD51,17.0,...,9.0,9.0,2.0,68.0,34.0,21.0,16.0,11.0,5.0,10.0
2084,2026-422,Cincinnati Masters,Hard,96.0,M,O,20260824,95.0,F0F1,21.0,...,6.0,4.0,4.0,69.0,27.0,18.0,23.0,11.0,4.0,8.0

### Instantiating data columns for useful extra statistics

In [ ]:
# instantiate a new column in the data with an arbitary elo rating

df['winner_elo'] = 1500

df['loser_elo'] = 1500

df['winner_ema_serve_accuracy'] = 0 # arbitary value

df['loser_ema_serve_accuracy'] = 0 

df['winner_surface_h2h_last_5'] = 0.5

df['loser_surface_h2h_last_5'] = 0.5 


df['winner_h2h_last_5'] = 0.5

df['loser_h2h_last_5'] = 0.5

#### Looping through the data

In [ ]:
def calc_elo_update(match_idx, who):

    k = 32
    default_elo = 1500

    player = df.iloc[match_idx][who]
    date = df.iloc[match_idx]['date']

    prev_match_filter = (((df[who] == player)) & (df['date'] < date))

    prev_matches = df[prev_match_filter]

    if not prev_matches.empty:
        prev_match = prev_matches.iloc[-1]  # assumes df sorted by date ascending

        player_match_outcome = int(prev_match['winner_id'] == player)

        if player_match_outcome == 1:
            players_elo = prev_match['winner_elo']
            opponents_elo = prev_match['loser_elo']
        else:
            players_elo = prev_match['loser_elo']
            opponents_elo = prev_match['winner_elo']

        player_expectation = 1 / (1 + 10 ** ((opponents_elo - players_elo) / 400))
        player_elo_update = players_elo + k * (player_match_outcome - player_expectation)

        return player_elo_update

    else:
        return default_elo
    

def calc_surface_h2h(match_idx):

    winner = df.iloc[match_idx]['winner_id']
    loser = df.iloc[match_idx]['loser_id']
    surface = df.iloc[match_idx]['surface']
    date = df.iloc[match_idx]['date']

    prev_matches_filter = ((df['winner_id'] == winner) & (df['loser_id'] == loser) & (df['date'] < date) & df['surface'] == surface)

    prev_matches = df[prev_matches_filter]

    if prev_matches.shape[0] >= 0:
        if prev_matches.shape[0] < 5:
            max = prev_matches.shape[0]
        else: 
            max = 5

        for prev_match in  range(0, max, prev_matches):

            

    if prev_matches.shape[0] >= 5:

        prev_matches = prev_matches.iloc[-5:]  # assumes df sorted by date ascending

        wins = 0 # instantiate the expo 

        losses = 0 #


        player_match_outcome = int(prev_match['winner_id'] == player)

        if player_match_outcome == 1:
            players_elo = prev_match['winner_elo']
            opponents_elo = prev_match['loser_elo']
        else:
            players_elo = prev_match['loser_elo']
            opponents_elo = prev_match['winner_elo']

        player_expectation = 1 / (1 + 10 ** ((opponents_elo - players_elo) / 400))
        player_elo_update = players_elo + k * (player_match_outcome - player_expectation)

        return player_elo_update

    else:
        return default_elo

In [ ]:
# loop through each match in the data

for match_idx, match in enumerate(df):

    # update elo

    df['winner_elo'], df['loser_elo'] += calc_elo_update(match_idx, 'winner_id') , calc_elo_update(match_idx, 'loser_id')

    # update h2h 

    


    # update h2h

In [ ]:
# calculating extra stats bare minimum for now

# calculate serve accuracy exponential moving average

# calculate elo



# calculate the on surface head to head exponential moving average

# calculate all surface head to head exponential moving average

Spliting Data into training, validation and test subsets

In [ ]:
# training data is all the data from until 2025 

training_data = df[df['tourney_date'] <= 20260101]

# validation data is 2026 until the tournement start

validation_data = df[df['tourney_date'] < 20260823]

# test data is the US Open matchdes but need to download these once they are available